version: '3.8'
services:
  event_postgres:
    image: postgres:16.4
    container_name: event_postgres
    environment:
      POSTGRES_DB: eventdb
      POSTGRES_USER: eventuser
      POSTGRES_PASSWORD: eventpass
    ports:
      - "5432:5432"
    networks:
      - event-network

  weather_postgres:
    image: postgres:16.4
    container_name: weather_postgres
    environment:
      POSTGRES_DB: weatherdb
      POSTGRES_USER: weatheruser
      POSTGRES_PASSWORD: weathertpass
    ports:
      - "32801:5432"
    networks:
      - event-network

  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - event-network

  kafka:
    image: confluentinc/cp-kafka:7.6.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
    networks:
      - event-network

  event-service:
    build: ./event-service
    container_name: event-service
    depends_on:
      - event_postgres
      - kafka
    environment:
      - DB_HOST=event_postgres
      - DB_PORT=5432
      - DB_USERNAME=eventuser
      - DB_PASSWORD=eventpass
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    networks:
      - event-network
    ports:
      - "8080:8080"

  weather-service:
    build: ./weather-service
    container_name: weather-service
    depends_on:
      - weather_postgres
      - kafka
      - event-service
    environment:
      - DB_HOST=weather_postgres
      - DB_PORT=5432
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - EVENT_API_URL=http://event-service:8080
    networks:
      - event-network
    ports:
      - "8082:8080"

networks:
  event-network:
    driver: bridge