version: '3.8'
services:
  postgres:
    image: postgres:16.4
    container_name: event_postgres
    environment:
      POSTGRES_DB: eventdb
      POSTGRES_USER: eventuser
      POSTGRES_PASSWORD: eventpass
    ports:
      - "5432:5432"
