server:
  port: ${SERVER_PORT:8090}

spring:
  application:
    name: '@name@'
  flyway:
    enabled: true
    locations: classpath:db/migration
  datasource:
    url: jdbc:postgresql://localhost:32801/weatherdb
    username: weatheruser
    password: weathertpass
    driver-class-name: org.postgresql.Driver
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    admin:
      properties:
        bootstrap.servers: ${spring.kafka.bootstrap-servers}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      transaction-id-prefix: tx-${spring.application.name}

  jpa:
    hibernate:
      ddl-auto: validate
weather-api:
  user-agent: "https://www.linkedin.com/in/csabacsak/ csabacsakcareer@gmail.com"
  url: "https://api.met.no"

event-api:
  url: "http://localhost:8080"
