server:
  port: ${SERVER_PORT:8090}

spring:
  application:
    name: '@name@'
  flyway:
    enabled: true
    locations: classpath:db/migration
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:32801}/weatherdb
    username: ${DB_USERNAME:weatheruser}
    password: ${DB_PASSWORD:weathertpass}
    driver-class-name: org.postgresql.Driver
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    admin:
      properties:
        bootstrap.servers: ${spring.kafka.bootstrap-servers}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      transaction-id-prefix: tx-${spring.application.name}

  jpa:
    hibernate:
      ddl-auto: validate
weather-api:
  user-agent: ${WEATHER_API_USER_AGENT:"https://www.linkedin.com/in/csabacsak/ csabacsakcareer@gmail.com"}
  url: "https://api.met.no"

event-api:
  url: "http://localhost:8080"

event-topic: "weather-topic"
