server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: '@name@'
  flyway:
    enabled: true
    locations: classpath:db/migration
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/eventdb
    username: ${DB_USERNAME:eventuser}
    password: ${DB_PASSWORD:eventpass}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    admin:
      properties:
        bootstrap.servers: ${spring.kafka.bootstrap-servers}
    consumer:
      group-id: event-group-id
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

event-topic: "weather-topic"
